### ISSUE TITLE
Fallo PWM manual

### ISSUE THREAD

**Issue by Tjchispas** [pablozg/freeds#1]
Hola, ante todo darte las gracias por el curro que te has pegado.
El problema que le encuentro es que al activar el PWM manualmente en la monitorización web del esp si aparece el porcentaje correcto, pero por mqtt envía uno totalmente diferente en 50% por mqtt envía pwm=283 mi derivador esta conectado por mqtt y funciona de 0 a 100, no he podido probar con energía solar era demasiado tarde, en caso de que necesites mas datos o servir de betatester no dudes en contactar. Saludos

**Comment by pablozg** [comment]
Hola, efectivamente era un fallo a la hora de convertir el valor de pwm para enviarlo por mqtt, bájate los binarios que acabo de subir y actualizas mediante la página web. No importa el orden, solamente tienes que esperar a que reinicie para actualizar el siguiente.

**Comment by Tjchispas** [comment]
Ahora perfecto gracias, al 50% 750w de mi termo de 1500w, me gusta el modo de actualizar muy simple y efectivo.
Una petición para futuras versiones, puedes poner el configurar uno de los relés mqtt como un pwm mqtt, tengo un ESP8266 con tasmota configurado como dimmer y lo enlazo con el porcentaje de pwm mediante node red, pero hacerlo desde el FreeDs seria mucho mas fácil y podría usarlo mas gente.

**Comment by pablozg** [comment]
No te entiendo con lo del relé pwm mqtt. ¿Puedes poner un ejemplo?

Respecto a lo del mqtt, el manual está puliendose, pero estos son los comandos por mqtt que puedes usar:

freeds/cmnd/pwm -> Acepta 1 para encender y 0 para apagar
freeds/cmnd/pwmman -> Acepta 1 para manual y 0 para auto
freeds/cmnd/pwmmanvalue -> Acepta valores de 0 a 100 que corresponde al % en modo manual
freeds/cmnd/screen -> Acepta valores de 0 a 4 corresponden a las pantallas de información en el oled
freeds/cmnd/pwmfrec -> Acepta valores entre 0 y 3000 corresponde a la frecuencia pwm
freeds/cmnd/brightness -> Acepta valores de 0 a 100 % corresponde al brillo de la pantalla

**Comment by Tjchispas** [comment]
A cojonudo que ya tienes implementados los comandos, perfecto crearé algunos switch en HA

Le que no he sido capaz de explicarte es simplemente que uno de los 4 reles que de pueden configurar desde la web sea un pwm por mqtt con tasmota

**Comment by Tjchispas** [comment]
![Captura de pantalla 2020-03-08 22 01 54](https://user-images.githubusercontent.com/21312679/76171192-d67a3080-6188-11ea-98c2-78fc9478140d.png)

**Comment by pablozg** [comment]
Lo que quieres hacer es que cuando se active el relé envie un comando mqtt que tu elijas, en este caso uno para activar un switch en tasmota, no?

**Comment by Tjchispas** [comment]
No exactamente lo que debe de enviar el el porcentaje pwm para que el tasmota configurado como dimmer actué sobre el dimmer físico, el esp32 no esta conectado físicamente al dimmer, por eso uso node red no encontré otro modo de enlazarlos, tampoco tengo los conocimientos suficientes

**Comment by pablozg** [comment]
Vale, pero además de enviar el pwm con valor, el tema lo debes escribir tú, ya que si no lo indicas no hay forma de saber a quien enviarlo. 

Ok, lo tengo en cuenta y pensaré como integrarlo.

**Comment by altusis1** [comment]
hola

**Comment by altusis1** [comment]
hola pablozg. Muchas gracias por compartir esta maravilla de programa.
Tengo algunas dudas que si puedes me gustaria aclarases.
1-Tenéis algún grupo en telegram?
2-tengo sdm120 + Módulo TTL a RS485(xy-017)+ esp2866. Con lo que consigo que la info que aporta el sdm la paso a home assistant mediante mqtt. Puedo usar esto para conectarlo a freeds?
Un saludo muchas gracias por tu gran aporte.

**Comment by vacarisses** [comment]
Hola,
el topic freeds/cmnd/pwmman a 0 para poner el PWM en AUTO no funciona, podrias poner un listado de topics.

Gracias

**Comment by pablozg** [comment]
Gracias por el aviso, ya está solucionado, en cuanto pueda subo la nueva versión que será la 1.0.3.

Un poco más arriba puse el listado de comandos mqtt actuales, pero te los vuelvo a poner aquí, si creéis necesario alguno más indicarlo.

````
freeds/cmnd/pwm -> Acepta 1 para encender y 0 para apagar
freeds/cmnd/pwmman -> Acepta 1 para manual y 0 para auto
freeds/cmnd/pwmmanvalue -> Acepta valores de 0 a 100 que corresponde al % en modo manual
freeds/cmnd/screen -> Acepta valores de 0 a 4 corresponden a las pantallas de información en el oled
freeds/cmnd/pwmfrec -> Acepta valores entre 0 y 3000 corresponde a la frecuencia pwm
freeds/cmnd/brightness -> Acepta valores de 0 a 100 % corresponde al brillo de la pantalla
````

**Comment by vacarisses** [comment]
Perfecto!!! Gracias, para mi con eso ya puedo automatizar en homeassistant, por otro lado, como puntalización ayer monte el ESP01 y en la web, no aparece que hay que puentearlo para que funcione, hasta que no lo hice no me funciono, solo como dato.

Gracias por tu proyecto y por tu ayuda

**Comment by lito333** [comment]
Hola amigo gran trabajo.
Yo no puedo conectarlo porque el inversor que tengo es un easun power 5kw y no esta en la lista,pero tengo el icc solar que tiene mqtt.
mi pregunta es no se puede conectar mediante mqtt al icc solar,si es asi hay algun manual o alguna guia,
gracias y un saludo
