### ISSUE TITLE
Victron PV inverter

### ISSUE THREAD

**Issue by siartec** [pablozg/freeds#108]
Hola a todos. Estoy conectado al Victron Cerbo pero la producción solar no aparece en Freeds. Cerbo lee los valores del inversor SMA SunnyBoy Primo. ¿Qué es posible hacer?
Gracias.
![Screenshot 2024-06-03 at 10-07-50 FreeDS (freeds_A630)](https://github.com/pablozg/freeds/assets/58388947/9943e789-2afb-432e-9716-e73fe73de0fb)
![Screenshot 2024-06-03 at 10-07-22 Remote Console on LAN](https://github.com/pablozg/freeds/assets/58388947/64143773-0560-40d3-ac9c-0267bd56d9f6)

**Comment by pablozg** [comment]
Prueba a poner en la consola el comando "useSolarAsMPTT 1" debería salir como solar todo lo que esté conectado al AcIn y AcOut.

**Comment by siartec** [comment]
Perfecto, ya está funcionando. Muchas gracias. ¿Pero cuál es el motivo por el que no funciona normalmente?

**Comment by pablozg** [comment]
Básicamente victron tiene muchas posibilidades de configuración y según hagas una u otra se debe activar la medida con esa opción en particular, yo me basé en las peticiones de los usuarios de victron para hacerlo, ya que no dispongo de él.
