### ISSUE TITLE
Medidor de corriente Orno OR-WE-514

### ISSUE THREAD

**Issue by jvfrsa** [pablozg/freeds#11]
Hola

He estado mirando soluciones para modbus.

Las que propones son buenas
He visto este Medidor modbus que lo usan mucho.
https://github.com/gituser-rk/orno-modbus-mqtt es barato y funciona bien.

He intentado compilar tu codigo para incluirlo y no he sido capaz.

Seria posible incluirlo? O ayudarme a configurar el IDE para hacerlo yo mismo

Gracias

**Comment by pablozg** [comment]
Hola, por el momento estoy algo liado y el hiking que soporta freeds es incluso más barato que el que propones. Por lo que por el momento no creo necesario incluirlo, pero siempre puedes intentar incluirlo basándote en el código existente del sdm120/240, tan sólo tienes que cambiar los registros que lee.
