### ISSUE TITLE
Uso con Hibridos

### ISSUE THREAD

**Issue by SolarCanarias** [pablozg/freeds#13]
Hola Pablo,
Primero gracias por tu trabajo que es fantástico y relamente lo que buscaba para aprovechar la energia solar en horas de maxima radiación.
Tengo el sistema montado en un ESP8266 con una tarjeta low cost y conectado a un Axpert King (Hibrido) y enviando datos a Domoticz mediante una raspberry pi con ICC. 
Creo que hay un error en los parámetros enviados a Domoticz ya que se envian los IDX al contrario de como esta en la pagina (IDX PWM en lugar de IDX Auto/manual y al revés). De momento simplemente he intercambiado los IDX de domoticz y funciona correctamente.
Hay un tema que no he conseguido hacer funcionar: el automatico, ya que en los híbridos de aislada no es la potencia de red la que indica "los sobrantes" sino que tiran de batería a medida que se quedan sin solar. Sería posible implementar la lectura y cuando por ejemplo no se cargue la bateria sea este el indicativo de falta de potencia solar?

Saludos

**Comment by pablozg** [comment]
Hola, el tema de domoticz lo he comprobado y no le encuentro el fallo, revisa tu configuración y vuelve a intentarlo, sobre lo de hacerlo para instalaciones offgrid lo estamos sopesando y cuando tenga algo de tiempo me pondré a ello.

Te aconsejo que si no estás en el grupo de telegram te suscribas ya que las dudas son respondidas más rápidamente allí.

https://t.me/freeds_es

Un saludo.
