### ISSUE TITLE
Medidor Shelly EM y regulador de potencia 10000W

### ISSUE THREAD

**Issue by patorbor** [pablozg/freeds#14]
Hola,

Primero felicitar a los desarrolladores por este proyecto.

Por otra parte, no encuentro como poder configurar un medidor Shelly EM en FreeDS.

Aparte, tengo el siguiente regulador de potencia funcionando:
https://www.amazon.es/10000W-Regulador-Voltaje-Digital-Controlador/dp/B075QVVP1P

Me gustaría saber si puedo aprovecharlo sustituyedo la unidad de control SCR por el ESP32.

Este regulador es mucho mas económico que el de Krida y soporta mas potencia.

Un saludo.

**Comment by pablozg** [comment]
Hola, ese regulador no es compatible, y para usar el shelly tan solo tienes que elegirlo en el menú desplegable, y configurar su ip dentro de freeds, tambien es importante que no lo tengas con usuario/clave, ya que no será capaz de leer los datos.

En caso de duda suscríbete al canal de freeds en telegram:

https://t.me/freeds_es
