### ISSUE TITLE
Publicaciones por mqtt Fronius

### ISSUE THREAD

**Issue by usuariokike** [pablozg/freeds#15]
Hola, enhorabuena por este trabajo que nos ayuda a muchos, cada vez se publican más datos por mqtt , muchos de ellos a lo mejor no nos hacen falta, se podrían seleccionar los que queremos que se publiquen, es para aligerar el servidor.
Gracias.

**Comment by pablozg** [comment]
Hola, los brokers, por ejemplo mosquitto, están preparados para soportar una gran carga de datos, y el poder seleccionar que topics se han enviar es mucho más trabajo que el beneficio que se obtiene, por lo que si en tu caso no quieres tener tantos topics, siempre puedes compilar tu propia versión y eliminar los que no necesites.

Saludos.
