### ISSUE TITLE
Lectura del SOC bateria incorreccto( a traves de BMV Victron)

### ISSUE THREAD

**Issue by jarjarbeens** [pablozg/freeds#17]
Hola muy buenas,
Actualmente estoy utilizando el derivador con el ICC Solar y funciona perfectamente, pero la nueva funcionalidad "FUNCIONAMIENTO EN INSTALACIÓN AISLADA O CON BATERÍAS" no me funciona como debería. Si le digo que empiece a derivar a partir de un nivel de SOC en concreto de la batería, este lo ignora y siempre esta en derivación.
Me he dado cuenta que en la pestaña de monitorización siempre sale que el nivel de batería esta al 100% cuando es incorrecto.
(Comparo este valor directamente con lo que me reporta ICC Solar y el BMV de Victron)
Creo que el problema reside en el Topic que lee el FreeDS para saber el SOC de nuestra bateria. Diría que el FreeDS utiliza "Inverter/BatterySOC". Esto es un problema para la gente que tenemos un BMV, que es este caso el Topic correcto a leer para saber el estado real de la batería es "BMV/SOC".
Ambos Topics son correctos, pero esto dependerá de la configuración de usuario. Creo que la mejor opción es que bajo la opción "FUNCIONAMIENTO EN INSTALACIÓN AISLADA O CON BATERÍAS" este tuviera un selector para indicar si disponemos de BMV o no. Así el SW sabría que valor seria el correcto que muestra el estado real del SOC.
Si no fuera posible la opción que comento, ¿Cómo podría hacer el cambio para que me lea correctamente este valor?
Un saludo y gracias de antemano.

**Comment by pablozg** [comment]
Ya está implementado para la próxima versión, gracias.
