### ISSUE TITLE
Wibeee se reinicia

### ISSUE THREAD

**Issue by robertofilipe** [pablozg/freeds#19]
Hola Pablo, tengo ESP32 funcionando correctamente con Shelly EM pero con Wibeee se reinicia constantemente. Cuál podría ser la solución?
Gracias

**Comment by pablozg** [comment]
Hola, es un fallo conocido de wibeee, pero con los últimos cambios que he realizado parece que están solucionados, lo podrás probar en la próxima versión.

**Comment by robertofilipe** [comment]
Hola Pablo, muchas gracias por tu dedicación al proyecto. Tan pronto como la próxima versión esté disponible, haré la actualización. Gracias

**Comment by pablozg** [comment]
Si te unes al canal de FreeDs en telegram te puedo mandar una versión de prueba para que hagas pruebas y me dices si funciona mejor en tu caso.

http://t.me/freeds_es

**Comment by robertofilipe** [comment]
Hola, sí ya era parte de Telegram. Que sería genial. Enviaré un mensaje en Telegram. Gracias
