### ISSUE TITLE
#Bug mqtt Victros + Fronius

### ISSUE THREAD

**Issue by enfelo** [pablozg/freeds#23]
Hola Pablo enhorabuena por tu trabajo, estoy probando la combinación de victron multiplus II + Fronius, la configuración la tengo para Victron modbus TCP.
Hay ciertos valores que no se publican por mqtt como: Potencia Solar, Potencia Diaria, Consumo Actual, SOC de la batería y consumo de Batería en W.

Una cosa más, supongo que te habrás dado cuenta, cuando la batería está cargada es habitual que cambie de descarga a carga y si tenemos excedentes pasas la señal PWM a "0%" esto hace  al sistema inestable , ya que si tenemos excedentes.
 Yo no resetearía la señal PWM ya que si hay excedentes.
Saludos y gracias por todo.

![freeds02](https://user-images.githubusercontent.com/80711330/115110875-c92f9800-9f7d-11eb-9dcd-8a82f1f666ae.jpg)
![freeds03](https://user-images.githubusercontent.com/80711330/115110880-ccc31f00-9f7d-11eb-81d0-bc108adad9e5.jpg)

**Comment by pablozg** [comment]
Hola, te pido que escribas estas dudas en el canal de telegram, ya que ahora mismo ando liado en el trabajo y tengo el proyecto en pausa hasta que saque tiempo.

En el grupo hay varios usuarios con victron que seguro te pueden ayudar, y respecto al tema de mqtt, escribe un mensaje con el hastag #bug para cuando me ponga con él encuentre rápidamente los mensajes.

https://t.me/freeds_es
