### ISSUE TITLE
Placa de potencia

### ISSUE THREAD

**Issue by Moradventure** [pablozg/freeds#26]
Hola.
Soy nuevo por aquí, en primer lugar felicitar a los desarrolladores por este proyecto.
Planteo mi problema por si a alguien le ha sucedido antes. Tengo configurado Freeds, con la visualización web correcta y corriendo la rutina correctamente, modificando los parámetros y con la lectura de consumo desde un medidor SDM 120, la lógica de control de escedente en la visualización funciona correctamente. 
Sin embargo en la placa de potencia, alimentada a 230v, en la salida me da permanentemente 230v en vacío, 0v si le conecto la resistencia del termo electrico de 1500w y 20v si le conecto una bombilla. No consigo tener alimentacion ni regulación al termo. No se si la placa de potencia viene mala o algo estoy haciendo yo mal. La placa de potencia es la Tindie.
Agradezco cualquier comentario.
Un saludo.

**Comment by pablozg** [comment]
Hola, este repositorio es sólo para mantener el código, no se da soporte a los problemas de funcionamiento desde aquí.

Por eso te recomiendo que entres al grupo oficial de Telegram usando el siguiente enlace y formules allí tu consulta.

https://t.me/freeds_es

Saludos.
