### ISSUE TITLE
Salidas encendidas al reiniciar

### ISSUE THREAD

**Issue by xipinformatic** [pablozg/freeds#27]
Las salidas del freeds se encienden todas al reiniciar independientemente de los valores configurados seria interesante que al reiniciarse estuvieran apagados o segun excedente ya que pueden consumir electricidad innecesaria si lo tenemos conectado a una bomba etc

**Comment by pablozg** [comment]
Hola, lo siento pero a mi no me ocurre, de hecho el firmware pone en nivel bajo (apagado) las cuatro salidas en cuanto se enciende o reinicia.

Como no soy capaz de replicar el problema, deberás hacer algunas pruebas y medir directamente las salidas que tienes conectadas a relé usando un polímetro para descartar que sea un problema de las placas de relé. 

Cualquier prueba que hagas coméntalo en el grupo de telegram para que lo lea en cuanto pueda.

Gracias.
