### ISSUE TITLE
Error conectar wifi solax v2 local

### ISSUE THREAD

**Issue by polcino** [pablozg/freeds#29]
Hola, buenas noches. Ante todo dar las gracias a pablozg y a la gente que esta trabajando en este proyecto.

No se si estoy haciendo algo mal, pero despues de seleccionar la wifi local del solax y meter la clave, el ESP32 reinicia y siempre me dices ERROR WIFI.

He probado con la 1.0.7 beta, la 1.0.7 Final y la 1.0.6 todas con el mismo resultado.

He cambiado la clave de la wifi local, mismo error, sin embargo a la wifi de casa si conecta bien.

No se si hago algo mal o es algun otro tipo de problema.

Saludos

**Comment by xelect75** [comment]
Olá, parabens por todo o trabalho neste projecto.
Eu não consigo conectar na minha rede DHCP, dá sempre "Error Wifi"
quais são os requisitos para conectar correctamente numa rede wifi?
Obrigado,
Nelson

**Comment by RoyGeova07** [comment]
Hola, todo esta bien
