### ISSUE TITLE
Conexión a Solax y "meter Hiking"

### ISSUE THREAD

**Issue by fmiguelpacheco** [pablozg/freeds#31]
Buenas tardes.
Increíble el trabajo que hacéis.
Sería posible conectar FreeDS a Solax Wifi v2 Local para obtener sus datos y a la vez al meter Hiking modbus para obtener el consumo total de la vivienda?
Sería una buena solución para tener todos los datos en una misma Web usando un meter económico.

**Comment by pablozg** [comment]
Siento el retraso, por el momento no es viable realizar dos peticiones a distintas fuentes de datos, pero si que lo podrías hacer mediante nodered y enviar los datos en formato json a través de mqtt.
