### ISSUE TITLE
Gestor de excedentes freeds para solax

### ISSUE THREAD

**Issue by Luissantospumar** [pablozg/freeds#37]
Hola Pablo,

Me pongo en contacto para ver si me puedes ayudar, llevo peleándome con el último paso de conexión del gestor de excedentes mi inversor solax generación 3. Creo que lo he probado todo. Logro conectar el esp32 ; me conecto al freeds y me enlazo con el pocket wifi del solax. Para engancharme a la red del pincho necesito apagar el wifi de casa. Una vez conectado lo pongo en modo local y en los ajustes de red pongo el wifi del pincho, pero en ningún momento se conecta y me salen los datos. No sé si me puedes ayudar, dar algún consejo, que te dé algún dato más; he seguido el proceso que indicas en los videos y estoy un poco desesperado, no se si se tiene que hacer a través de MQTT. Un saludo y muchas gracias por tu trabajo y contribución.

**Comment by pablozg** [comment]
Hola, léete el manual que está disponible en el anclado del grupo de telegram, en él se explica como puedes evitar apagar el router y demás, cambiando el firmware al pincho y poder hacerlo desde la red principal.

En caso de duda pregunta en el grupo que muchos usuarios lo tienen así y si buscas en mensajes anteriores te saldrá también la explicación.

https://t.me/freeds_es

Gracias,
