### ISSUE TITLE
tasmota json example

### ISSUE THREAD

**Issue by fapgomes** [pablozg/freeds#42]
Hi,

 It's possible to send an example of the json format to send to freeds? I need to see how to send the current water temperature to freeds.

Best Regards,
Fernando Gomes

**Comment by fapgomes** [comment]
Hi? Any news about this?

Thanks,

**Comment by pablozg** [comment]
Hi, you must read the manual at [https://docs.google.com/document/d/1-XLCqHEbpqEPi4geI4CbANmGxodExC__zDvND89xjIU/edit#](url), in the page 25 you have the info about it, but you can't to send the water temperature to freeDS, you must connect a temp sensor to it.

**Comment by fapgomes** [comment]
Hi,

I'm using a json based on the manual, but it doesn't have the option to pass the temperature (I had to connect one directly) and additionally I had to send two json to have the consumption of the house. 

Another thing, I've to drop the first `{"Status":`

Best Regards,
Fernando Gomes
