### ISSUE TITLE
FreeDS para Trifasico ?

### ISSUE THREAD

**Issue by 1966pjrl** [pablozg/freeds#43]
Me gustaría usar FreeDS para reemplazar el calentamiento de agua con diesel para resistencia eléctrica.
Pero como tengo una instalación trifásica y la producción solar solo se inyecta en una de las fases, no lo estoy consiguiendo ...
Tengo un medidor Shelly 3EM (con tres pinzas, una en cada Fase) para publicar en HomeAssistant MQTT Base los valores de consumo de la red.
Tengo una Shelly EM con una pinza que monitoriza la producción solar, y también publico la producción solar en la base de datos HomeAssistant MQTT.

¿Cómo puedo utilizar FreeDS?

Con Nod-red agregué en una variable la potencia de las 3 fases de (Shelly 3EM)
Tengo el valor de producción solar de (SHelly EM)
¿Cómo puedo pasar estos valores a FreeDS?

Muchas gracias por todo el conocimiento compartido y enhorabuena por el excelente proyecto, a quienes quiero agradecer a los responsables de compartir en esta comunidad que tanto me ha hecho aprender.

Pido disculpas por mi castellano ...

**Comment by pablozg** [comment]
Hola, puedes usar el modo mqtt de freeDS y enviarle los datos en una cadena json, léete el manual [https://docs.google.com/document/d/1-XLCqHEbpqEPi4geI4CbANmGxodExC__zDvND89xjIU/edit#](url) y en la página 25 muestra en ejemplo de la cadena json que puedes enviar mediante node-red.

Te recomiendo que te unas al grupo de freeDS en telegram para obtener respuestas más rápidas a tus dudas [https://t.me/freeds_es](url). 

Un saludo.
