### ISSUE TITLE
Solar Pv production

### ISSUE THREAD

**Issue by toyosupra** [pablozg/freeds#45]
Hello

I am using freeds for the first time and I use version 1.1.0 beta,  everything isworking but the graph from solar pv didnt show production:

![Screenshot_20211106-123510_Chrome](https://user-images.githubusercontent.com/35711800/140610195-fc533a75-ebe8-4f3c-8642-f5e62a50bfd6.jpg)

**Comment by pablozg** [comment]
Hi, please join telegram group [https://t.me/freeds_es](url) and ask your question there, you must provide more info, like what inverter are you using, etc.

Thanks.
