### ISSUE TITLE
Añadir la opción de definir fondo de escala para dial solar

### ISSUE THREAD

**Issue by SergioEscuder** [pablozg/freeds#50]
Hola, increíble trabajo este proyecto. Enhorabuena!

Con el fin de poder ver desde la distancia en un Dashboard la producción solar aproximada, sería interesante añadir la opción de definir fondo de escala para el dial gauge solar. De esta forma si tienes 6kwp. Y ves que el dial está azul hasta la zona central, sabes que estás generando unos 3kwp.

**Comment by pablozg** [comment]
Lo siento pero por el momento no es posible, ya que lo valores máximos se actualizan automaticamente según la produción / consumo que tengas y se almacena en la caché del navegador.

Por ello si quieres tener una referencia tendrás que usar los navegadores que quieras para monitorizar y esperar que obtenga el valor máximo, pero ten en cuenta que si borras la caché esos datos se perderán.
