### ISSUE TITLE
Configurar data e hora

### ISSUE THREAD

**Issue by jescampos** [pablozg/freeds#51]
É possível configurar data e hora? Definir um time zone? Ntp server? 

É possível aceder por SSH para configurar directamente no S.O.?

**Comment by miselfi1** [comment]
e ler o manual?

**Comment by jescampos** [comment]
Não fala nada sobre ntp e SSH.

**Comment by miselfi1** [comment]
é feito na cansola web
vê o codigo fonte tem lá um ficheiro que se chama timeQUAQUERCOIAS.txt,
copia a linha que quiseres e cola na consola...
o ntp é feito por essa linha nativamente

**Comment by jescampos** [comment]
Obrigado. 👍

**Comment by jescampos** [comment]
Afinal estava no Manual. Obrigado mais uma vez. 👍

**Comment by miselfi1** [comment]
👍

**Comment by valimaties** [comment]
I tried sending the text from the TimeZones.txt, I mean the line I interest, into the console... but nothing is happening:

```
"Europe/Bucharest","EET-2EEST,M3.5.0/3,M10.5.0/4"
```

I sent this in console, and nothing happening... 

OK... Finally, I found it in manual:

you must send the command
```
tzConfig EET-2EEST,M3.5.0/3,M10.5.0/4
```

So, the comand starts with `txConfig`, a space, and the second parameter from the line in `TimeZones.txt` file you want to. In my case, for `Europe/Bucharest`, I copied the `EET-2EEST....`

**Comment by miselfi1** [comment]
use only

EET-2EEST,M3.5.0/3,M10.5.0/4

**Comment by valimaties** [comment]
> use only
> 
> EET-2EEST,M3.5.0/3,M10.5.0/4
> […](#)

it didn't worked for me using only that text... I had to sent it as I said:

```
tzConfig EET-2EEST,M3.5.0/3,M10.5.0/4
```

**Comment by miselfi1** [comment]
hi

using wrong code...

"Asia/Nicosia","EET-2EEST,M3.5.0/3,M10.5.0/4"

that is for asia/nicosia...

Right one for europe/bucarest is:

"Europe/Budapest","CET-1CEST,M3.5.0,M10.5.0/3"

**Comment by valimaties** [comment]
> hi
> 
> using wrong code...
> 
> "Asia/Nicosia","EET-2EEST,M3.5.0/3,M10.5.0/4"
> 
> that is for asia/nicosia...
> 
> Right one for europe/bucarest is:
> 
> "Europe/Budapest","CET-1CEST,M3.5.0,M10.5.0/3"
> […](#)

<img width="463" height="346" alt="Image" src="https://github.com/user-attachments/assets/977499f4-a1af-4abc-86bb-25d82d6aaf2e" />

This is from TimeZones.txt, in the zip file of Pablo's firmware upgrade file:

<img width="270" height="259" alt="Image" src="https://github.com/user-attachments/assets/2710d997-7bcf-4c60-a349-2539ff1c1f12" />


Bucharest is the same as Athens.

And after using that code, it displays correct time and date.

**Comment by miselfi1** [comment]
somethings not right...
[image: Screenshot 2026-01-16 at 11.27.03.png]
[image: Screenshot 2026-01-16 at 11.27.42.png]
