### ISSUE TITLE
Battery SOC with Goodwe ES/EM

### ISSUE THREAD

**Issue by jorgestima** [pablozg/freeds#53]
In my case that I have a inverter Goodwe EM, the battery SOC value in FreeDS is wrong. For example, it shows 13568% when the real value is 53%. It seems that the shown value must be divided by 256 to get the corret SOC value.

Also, it shows the battery with negative power and providing power, which is wrong, because battery negative power means that it is charging.

![Goodwe EM](https://user-images.githubusercontent.com/35270552/155308972-e97b1ba4-4715-4613-b119-4eb52bb2ddc5.PNG)

**Comment by pablozg** [comment]
Please, check with the last beta again.

**Comment by ibm8999** [comment]
Buenas noches Pablo
Lo comenté por el grupo y te lo pongo por aquí también. 
La beta 12 funcionando perfectamente en GoodWe. 

Muchas gracias por tu trabajo 
Un saludo
Paco
