### ISSUE TITLE
Freeds browser error 

### ISSUE THREAD

**Issue by alyn304** [pablozg/freeds#63]
Hello. can you tell me what I'm doing wrong or why after loading one of the 1.0.7 or 1.1.0011 versions I can no longer access the program either from the desktop browser or from the phone browser, version 1.0.6 works, only the ones mentioned above I'm having problems, I'm using an esp32 oled board. I am attaching pictures of the board I use and the error that appears in my browser. thanks a lot
![20220908_185210](https://user-images.githubusercontent.com/113125292/189200615-f275a85a-9c63-46fa-89fb-604396b551d4.jpg)
![20220908_185204](https://user-images.githubusercontent.com/113125292/189200656-c7a289b6-d646-478c-9871-5d26403aec5f.jpg)

**Comment by pablozg** [comment]
Solved in telegram group, bad programming parameters.
