### ISSUE TITLE
problema derivacion

### ISSUE THREAD

**Issue by vacarisses** [pablozg/freeds#7]
Hola,
tengo un problema con el derivador, he probado varias versiones y con todas me falla. En algunos momentos el derivador se queda bloqueado al 19%, para desbloquear, pasando de auto-manual y manual-auto, se "desbloquea" y ya funciona bien.

**Comment by pablozg** [comment]
Hola, es un problema ya solucionado en la pre versión 1.0.5rev5, la puedes bajar de aquí:

https://github.com/pablozg/freeds/releases/download/1.0.5/FreeDS_Pre1.0.5Rev5.zip

**Comment by vacarisses** [comment]
Actualizado, muchas Gracias!!!!
