### ISSUE TITLE
fallo freeds

### ISSUE THREAD

**Issue by lito333** [pablozg/freeds#8]
Buenos dias pablo,no consigo que me funcione el freeds con el icc estoi arto de darle vueltas y no me va 
la pantalla marca bien los valores tanto de red como de produccion solar,y el pwm si lo activo yo manualmente el calentador si me funciona hasta el porcentaje que yo le ponga si le pongo un 50% pues calienta a un 50% si le pongo el 80% va hasta el 80%,
pero con el pwm  en automatico no enciende nunca el calentador aunque tenga una produccion solar de 2500w,
si cuando lo pongo el pwm en manual y esta funcionando el calentador,si lo paso a automatico va bajando el porcentaje hasta caer a cero y se apaga el calentadro.
si tienes alguna idea o puedes ponerme en contacto con algien que lo tenga funcionando con el icc 
para encontrar donde puedo tener el fallo,sino ya lo dejo por imposible porque ya no se que hacerle
un saludo

**Comment by pablozg** [comment]
Antes de tirar la toalla, ¿estás en alguno de los grupos de Telegram (Solares o SolaxX1)?, si es así contacta conmigo, pero necesito que me indiques con que signo te aparece en la página de monitorización la potencia de red cuando estás vertiendo a red, porque puede que sea el problema.

Si te aparece con signo negativo cuando en realidad estás vertiendo es un problema del software que se soluciona en un segundo,

Un saludo.

**Comment by lito333** [comment]
Si que te hablo por privado o por publico

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: pablozg <notifications@github.com>
Enviado: Wednesday, April 22, 2020 11:47:41 AM
Para: pablozg/freeds <freeds@noreply.github.com>
Cc: lito333 <lito333@hotmail.es>; Author <author@noreply.github.com>
Asunto: Re: [pablozg/freeds] fallo freeds (#8)


Antes de tirar la toalla, ¿estás en alguno de los grupos de Telegram (Solares o SolaxX1)?, si es así contacta conmigo, pero necesito que me indiques con que signo te aparece en la página de monitorización la potencia de red cuando estás vertiendo a red, porque puede que sea el problema.

Si te aparece con signo negativo cuando en realidad estás vertiendo es un problema del software que se soluciona en un segundo,

Un saludo.
