### ISSUE TITLE
Goodwe xs 

### ISSUE THREAD

**Issue by digomilo** [pablozg/freeds#80]
hola, estoy utilizando la version 15 beta, tengo un goodwe xs 2000, la lectura de la producion esta correcta, pero el consumo de la casa me da una lectura erronea. si gasta 100w me marca como que consume 1000, es un problema mio o puede ser algun bug de codigo? muchas gracias Seguir asi!

**Comment by pablozg** [comment]
Hola necesito más información, de los inversores goodwe no tengo casi feedback, puedes indicar exactamente con una captura donde está el dato erroneo? gracias.

**Comment by digomilo** [comment]
Hola, he estado informandome en grupo de goodwe, que usan freeds, y me han
comentado que el modelo xs, con su mete”homekit”, solo recibe dato del
inversor, y la lectura de vertido y consumo de la vivienda, solo lo envia
al portal sems. Por eso los datos no son correcto. De echo el unico dato
correcto que detecta el freeds es la produccion. Pero no detecta ningun
tipo de consumo de la vivienda. Me aconsejaron de usar un shelly em. Si
quieres mas informaciones te puedo pasar captura y mas, ya me diras! Muchas
gracias

Il giorno sab 8 apr 2023 alle 17:21 pablozg ***@***.***> ha
scritto:
