### ISSUE TITLE
Inversores que trabajan con salida RS232

### ISSUE THREAD

**Issue by nachoseg** [pablozg/freeds#81]
Hola Pablozg, tengo un inversor que trabaja con salida RS232, como podria implementar los datos de este inversor al FreeDs.
Un saludo y Gracias

**Comment by pablozg** [comment]
Con esa información es dificil ayudarte, tienes que encontrar como te facilita los datos el inversor a través del rs232, una vez lo sepas debes conectar algo que te haga de traductor, como una raspberry pi o similar y así poder enviar los datos mediante mqtt o alguno de los otros modos que soporte actualmente freeds.
