### ISSUE TITLE
Bucle con envoy

### ISSUE THREAD

**Issue by nunezruj88** [pablozg/freeds#84]
#bug_beta16

Al seleccionar origen de datos con envoy, se produce un bucle infinito y el ESP no arranca. Con shellyEM va bien.

https://user-images.githubusercontent.com/90215806/231537005-304ef081-5e52-490f-bcd4-59df15524a93.mov

**Comment by pablozg** [comment]
Hola, no ha habido cambios de la beta 15 a la 16 con el envoy, por lo que no entiendo el motivo por el que no funciona, si estás en el grupo de telegram, contacta en privado conmigo y te paso la ultima compilacion disponible, con algunas comprobaciones extras a la hora de obtener los datos, por si fuera ese el motivo.

**Comment by pablozg** [comment]
Solucionado en la Beta 17
