### ISSUE TITLE
Shelly 3EM con trifásico

### ISSUE THREAD

**Issue by asdecopes** [pablozg/freeds#87]
Hola Pablo,

Un par de cosillas sobre este Shelly.

a) Podrías mirar de integrar (poner un radiobutton) el comando use3PhasePower en la pestaña configuración cuando se usa el Shelly 3EM en trifásico. 
b) Se pondría documentar este parametro en el manual. Y si lo lee SolaresTV tambien ;)

Muchas gracias,
Jordi

**Comment by pablozg** [comment]
Hola, lo siento el menu ya está bastante cargado como para añadir una nueva opción que solo sirve para shelly cuando ya está la opción de meterlo mediante consola, respecto al manual, este es colaborativo por lo que si crees que se debe mejorar puedes entrar y solicitar desde el mismo manual que te den acceso a editarlo y hagas las ediciones oportunas.

Respecto a Francisco de solares TV, no creo que lo lea aquí ya que no forma parte de FreeDS, colabora en el grupo de telegram  pero no creo que se pase por aquí a leer las consultas, por lo que deberás comentárselo directamente a él.
