### ISSUE TITLE
Configurar las pinzas del Shelly Pro 3EM

### ISSUE THREAD

**Issue by sadesr** [pablozg/freeds#95]
Tengo la pinza C de mi Shelly Pro 3EM instalada en la fase del proveedor de energía y la pinza B en los paneles fotovoltaicos. ¿Es posible configurarlo de esta manera en el freeds o debo cambiarlo físicamente para que funcione correctamente?

**Comment by pablozg** [comment]
Por el momento no hay posibilidad de elegir la pinza de forma personalizada.

Un saludo.
