### ISSUE TITLE
Source Code not up-to-date with releases

### ISSUE THREAD

**Issue by zcsrf** [pablozg/freeds#97]
Hello,

Thanks for the great project.

It seems the source code is not up to date with the latests releases.
I only see branch "PID", and the source code seems to be from the final 1.0.7.
Could we get the rolling "beta" firmwares on a  development or release_candidate branch or something like that?

It would be nice to compile the latest version with custom defaults.

Best regards

**Comment by pablozg** [comment]
Hola, 

Actualmente el codigo de las betas es totalmente nuevo y por diversos motivos no es público, pero si libre de uso, si necesitas alguna mejora o tienes alguna sugerencia, puedes pasarte por el canal de telegram o dejarla por aquí.

Saludos.
